search_query: "4K MAUI LIVE CAM BEACH CAM"
webcam_url: "https://www.nps.gov/media/webcam/view.htm?id=56F5E0DC-9116-8502-7F673D0FF0B8378A"
# webcam_url: "https://www.skylinewebcams.com/zh/webcam/united-states/hawaii/maui/kahului.html"